### ISSUE TITLE
is it need http jar file or anything/

### ISSUE THREAD

**Issue by saravanan72** [amalChandran/LinkedInAndroid20#1]

**Comment by saravanan72** [comment]
hi, i am integrating this app with my sample project. it seems to be working pakka. but when am adding this, it  requires org.apache.http. did u use jar file or anything to use httpclient? please tell me..

**Comment by amalChandran** [comment]
I dont remember using it.

Btw, whats the exact error you are getting?

**Comment by amalChandran** [comment]
@saravanan72 close this if you have resolved this.
